#!/bin/bash

GAIADIR="$(pwd)/chain-code/gaia"

[ ! -d "$GAIADIR" ] && echo "Repositry for gaia does not exist at $GAIADIR. Try running 'make get-gaia'..." && exit 1

cd $GAIADIR
echo "Building gaiad binary at branch($(git branch --show-current)) tag($(git describe --tags)) commit($(git rev-parse HEAD))"
make install &> /dev/null
gaiad version --long
