#!/bin/bash
# two-chainz creates two fnsad chains and configures the relayer to 

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
FNSA_DATA="$(pwd)/data"
RELAYER_DIR="$(dirname $SCRIPTDIR)"
RELAYER_CONF="$HOME/.relayer"

# Ensure fnsad is installed
if ! [ -x "$(which fnsad)" ]; then
  echo "Error: fnsad is not installed. Try running 'make build-fnsa'" >&2
  exit 1
fi

# Display software version for testers
echo "FNSA VERSION INFO:"
fnsad version --long

# Ensure jq is installed
if [[ ! -x "$(which jq)" ]]; then
  echo "jq (a tool for parsing json in the command line) is required..."
  echo "https://stedolan.github.io/jq/download/"
  exit 1
fi

# Ensure user understands what will be deleted
if [[ -d $FNSA_DATA ]] && [[ ! "$1" == "skip" ]]; then
  read -p "$(basename $0) will delete \$(pwd)/data and \$HOME/.relayer folders. Do you wish to continue? (y/n): " -n 1 -r
  echo
  if [[ ! $REPLY =~ ^[Yy]$ ]]; then
      exit 1
  fi
fi

# Delete data from old runs
rm -rf $FNSA_DATA &> /dev/null
rm -rf $RELAYER_CONF &> /dev/null

# Stop existing fnsad processes
killall gaiad &> /dev/null
killall akash &> /dev/null
killall fnsad &> /dev/null

set -e

chainid0=fnsa-0
chainid1=fnsa-1

echo "Generating fnsa configurations..."
mkdir -p $FNSA_DATA && cd $FNSA_DATA && cd ../
./scripts/one-chain fnsad $chainid0 ./data 26657 26656 6060 9090 stake samoleans
./scripts/one-chain fnsad $chainid1 ./data 26557 26556 6061 9091 rice beans

[ -f $FNSA_DATA/$chainid0.log ] && echo "$chainid0 initialized. Watch file $FNSA_DATA/$chainid0.log to see its execution."
[ -f $FNSA_DATA/$chainid1.log ] && echo "$chainid1 initialized. Watch file $FNSA_DATA/$chainid1.log to see its execution."

cd $RELAYER_DIR

echo "Building Relayer..."
make -C ../../ install

pwd

echo "Generating rly configurations..."
rly config init
rly chains add-dir configs/chains

SEED0=$(jq -r '.mnemonic' $FNSA_DATA/fnsa-0/key_seed.json)
SEED1=$(jq -r '.mnemonic' $FNSA_DATA/fnsa-1/key_seed.json)
echo "Key $(rly keys restore fnsa-0 testkey "$SEED0") imported from fnsa-0 to relayer..."
echo "Key $(rly keys restore fnsa-1 testkey "$SEED1") imported from fnsa-1 to relayer..."

rly paths add-dir configs/paths
